apiVersion: 1  
  
datasources:  
  - name: WAF-SQLite
    uid: WAF-SQLite
    type: frser-sqlite-datasource  
    access: proxy  
    jsonData:  
      path: /var/lib/grafana/data-waf/waf_dashboard.db  
    isDefault: true  
    editable: true
